/// Character attribute IDs as used in skill configs, buff features, and condition params.
/// Source: CharacterEnum.AttrId (client Lua)
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[repr(i32)]
pub enum AttrId {
    LostHp = 99,
    CurrentHp = 100,
    Hp = 101,
    Attack = 102,
    Defense = 103,
    Mdefense = 104,
    Technic = 105,
    Cri = 201,
    Recri = 202,
    CriDmg = 203,
    CriDef = 204,
    AddDmg = 205,
    /// Reduces incoming damage by rate‰ (e.g. 300 = 30% damage reduction)
    DropDmg = 206,
    Revive = 209,
    Absorb = 210,
    Clutch = 211,
    Heal = 212,
    DefenseIgnore = 213,
    NormalSkillRate = 214,
    PlayAddRate = 215,
    PlayDropRate = 216,
    ReboundDmg = 218,
    ExtraDmg = 219,
    ReuseDmg = 220,
    PoisonAddRate = 301,
    HpBase = 601,
    AttackBase = 602,
    DefenseBase = 603,
    MdefenseBase = 604,
    HpPercent = 605,
    AttackPercent = 606,
    DefensePercent = 607,
    MdefensePercent = 608,
}

impl AttrId {
    pub fn from(val: i32) -> Option<Self> {
        match val {
            99 => Some(Self::LostHp),
            100 => Some(Self::CurrentHp),
            101 => Some(Self::Hp),
            102 => Some(Self::Attack),
            103 => Some(Self::Defense),
            104 => Some(Self::Mdefense),
            105 => Some(Self::Technic),
            201 => Some(Self::Cri),
            202 => Some(Self::Recri),
            203 => Some(Self::CriDmg),
            204 => Some(Self::CriDef),
            205 => Some(Self::AddDmg),
            206 => Some(Self::DropDmg),
            209 => Some(Self::Revive),
            210 => Some(Self::Absorb),
            211 => Some(Self::Clutch),
            212 => Some(Self::Heal),
            213 => Some(Self::DefenseIgnore),
            214 => Some(Self::NormalSkillRate),
            215 => Some(Self::PlayAddRate),
            216 => Some(Self::PlayDropRate),
            218 => Some(Self::ReboundDmg),
            219 => Some(Self::ExtraDmg),
            220 => Some(Self::ReuseDmg),
            301 => Some(Self::PoisonAddRate),
            601 => Some(Self::HpBase),
            602 => Some(Self::AttackBase),
            603 => Some(Self::DefenseBase),
            604 => Some(Self::MdefenseBase),
            605 => Some(Self::HpPercent),
            606 => Some(Self::AttackPercent),
            607 => Some(Self::DefensePercent),
            608 => Some(Self::MdefensePercent),
            _ => None,
        }
    }
}
