// Auto-generated by scripts/gen_effect_enums.py — do not edit manually.
// Target IDs from skill_effect conditionTarget / behaviorTarget fields.

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Target {
    AllAlly,       // 101
    AllEnemy,      // 102
    Self_,         // 103
    AllAllyNoSelf, // 104
    RandomAlly,    // 105
    RandomEnemy,   // 106
    Other(i32),
}

impl Target {
    pub fn entities(self, fight: &sonettobuf::Fight, owner_uid: i64) -> Vec<i64> {
        let side = if owner_uid >= 0 { fight.attacker.as_ref() } else { fight.defender.as_ref() };
        let ally: Vec<i64> = side.map_or(vec![], |s| {
            s.entitys.iter().chain(s.sub_entitys.iter()).filter_map(|e| e.uid).collect()
        });
        match self {
            Target::AllAlly => ally,
            Target::Self_ => vec![owner_uid],
            Target::AllAllyNoSelf => ally.into_iter().filter(|&uid| uid != owner_uid).collect(),
            other => {
                tracing::warn!("unimplemented target variant: {:?}", other);
                vec![]
            }
        }
    }

    pub fn from_id(id: i32) -> Self {
        match id {
            101 => Target::AllAlly,
            102 => Target::AllEnemy,
            103 => Target::Self_,
            104 => Target::AllAllyNoSelf,
            105 => Target::RandomAlly,
            106 => Target::RandomEnemy,
            v   => Target::Other(v),
        }
    }
}
